### ISSUE TITLE
layouts

### ISSUE THREAD

**Issue by davemillican** [TIY-Columbia-Front-End-Engineering/assignments-feb-2016#11]
https://github.com/davemillican/layouts

**Comment by davemillican** [comment]
changed the title of the issue.

**Comment by davemillican** [comment]
Done with this layout

**Comment by ericmcdaniel** [comment]
* You have some incorrect indentation in your markup 
[here](https://github.com/davemillican/layouts/blob/master/index.html#L9), [here](https://github.com/davemillican/layouts/blob/master/index2.html#L13) and [here](https://github.com/davemillican/layouts/blob/master/index3.html#L27)
