### ISSUE TITLE
layouts

### ISSUE THREAD

**Issue by johnwfaulk** [TIY-Columbia-Front-End-Engineering/assignments-feb-2016#13]
https://github.com/johnwfaulk/layouts

**Comment by johnwfaulk** [comment]
is this better?

**Comment by ericmcdaniel** [comment]
* On your first layout, you have some [excess](https://github.com/johnwfaulk/layouts/blob/master/src/css/index1.css#L38) [clears](https://github.com/johnwfaulk/layouts/blob/master/src/css/index1.css#L43) in your CSS when you are already clearing the columns via the `div.clear` element.
* You used margins throughout layout 3 where padding would have been more applicable. We can talk about this more during lab if you have questions.
