### ISSUE TITLE
layouts

### ISSUE THREAD

**Issue by DrewSancho** [TIY-Columbia-Front-End-Engineering/assignments-feb-2016#14]
https://github.com/DrewSancho/layout1

https://github.com/DrewSancho/layouts2

**Comment by DrewSancho** [comment]
https://github.com/DrewSancho/layout1.git

**Comment by DrewSancho** [comment]
the second one is the one with all the gits

**Comment by DrewSancho** [comment]
its finished

**Comment by ericmcdaniel** [comment]
if you're done with the assignment, close the issue. also, change the name of the issue to the name of the project, which is "layouts"

**Comment by ericmcdaniel** [comment]
In addition, change the name of your "layout1" repository to "layouts"

**Comment by DrewSancho** [comment]
https://github.com/DrewSancho/layouts

**Comment by DrewSancho** [comment]
The corrected git http and also corrected stupidity on my behalf

**Comment by ericmcdaniel** [comment]
* You used a `div` with inline styles to clear your columns on the first layout. I'm pretty sure I helped you add that element, and I know you used a class in the latter two layouts, but I am mentioning it as a friendly reminder that inline styles are usually bad.
