### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by davemillican** [TIY-Columbia-Front-End-Engineering/assignments-feb-2016#7]
Open issue for homework assignment
https://github.com/davemillican/survey.git

**Comment by davemillican** [comment]
Checked in for review

**Comment by ericmcdaniel** [comment]
Good work. Some feedback:

- You could have used labels for each of the radio buttons and checkboxes.
- Overall your HTML formatting looks good.
- You have a syntax error in your CSS file [here](https://github.com/davemillican/survey/blob/master/src/css/index.css#L19)
